// Copyright 2015 Google Inc. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: pb/build_proto/build.proto

package build_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Build struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Fingerprint, e.g. "google/mysid/toro:4.0.4/IMM06/243892:userdebug/dev-keys"
	Fingerprint *string `protobuf:"bytes,1,opt,name=fingerprint" json:"fingerprint,omitempty"`
	// Carrier, e.g. "google"
	Brand *string `protobuf:"bytes,2,opt,name=brand" json:"brand,omitempty"`
	// Product name, e.g. "mysid"
	Product *string `protobuf:"bytes,3,opt,name=product" json:"product,omitempty"`
	// Product name, e.g. "toro"
	Device *string `protobuf:"bytes,4,opt,name=device" json:"device,omitempty"`
	// Release version, e.g. "4.0.4"
	Release *string `protobuf:"bytes,5,opt,name=release" json:"release,omitempty"`
	// Build id, e.g. "IMM06"
	BuildId *string `protobuf:"bytes,6,opt,name=build_id,json=buildId" json:"build_id,omitempty"`
	// Incremental build id, e.g. "243892"
	Incremental *string `protobuf:"bytes,7,opt,name=incremental" json:"incremental,omitempty"`
	// Type of build, e.g. "userdebug"
	Type *string `protobuf:"bytes,8,opt,name=type" json:"type,omitempty"`
	// Tags, e.g. "dev-keys"
	Tags          []string `protobuf:"bytes,9,rep,name=tags" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Build) Reset() {
	*x = Build{}
	mi := &file_pb_build_proto_build_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Build) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Build) ProtoMessage() {}

func (x *Build) ProtoReflect() protoreflect.Message {
	mi := &file_pb_build_proto_build_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Build.ProtoReflect.Descriptor instead.
func (*Build) Descriptor() ([]byte, []int) {
	return file_pb_build_proto_build_proto_rawDescGZIP(), []int{0}
}

func (x *Build) GetFingerprint() string {
	if x != nil && x.Fingerprint != nil {
		return *x.Fingerprint
	}
	return ""
}

func (x *Build) GetBrand() string {
	if x != nil && x.Brand != nil {
		return *x.Brand
	}
	return ""
}

func (x *Build) GetProduct() string {
	if x != nil && x.Product != nil {
		return *x.Product
	}
	return ""
}

func (x *Build) GetDevice() string {
	if x != nil && x.Device != nil {
		return *x.Device
	}
	return ""
}

func (x *Build) GetRelease() string {
	if x != nil && x.Release != nil {
		return *x.Release
	}
	return ""
}

func (x *Build) GetBuildId() string {
	if x != nil && x.BuildId != nil {
		return *x.BuildId
	}
	return ""
}

func (x *Build) GetIncremental() string {
	if x != nil && x.Incremental != nil {
		return *x.Incremental
	}
	return ""
}

func (x *Build) GetType() string {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ""
}

func (x *Build) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

var File_pb_build_proto_build_proto protoreflect.FileDescriptor

const file_pb_build_proto_build_proto_rawDesc = "" +
	"\n" +
	"\x1apb/build_proto/build.proto\x12\vbuild_proto\"\xf0\x01\n" +
	"\x05Build\x12 \n" +
	"\vfingerprint\x18\x01 \x01(\tR\vfingerprint\x12\x14\n" +
	"\x05brand\x18\x02 \x01(\tR\x05brand\x12\x18\n" +
	"\aproduct\x18\x03 \x01(\tR\aproduct\x12\x16\n" +
	"\x06device\x18\x04 \x01(\tR\x06device\x12\x18\n" +
	"\arelease\x18\x05 \x01(\tR\arelease\x12\x19\n" +
	"\bbuild_id\x18\x06 \x01(\tR\abuildId\x12 \n" +
	"\vincremental\x18\a \x01(\tR\vincremental\x12\x12\n" +
	"\x04type\x18\b \x01(\tR\x04type\x12\x12\n" +
	"\x04tags\x18\t \x03(\tR\x04tagsB4Z2github.com/google/battery-historian/pb/build_proto"

var (
	file_pb_build_proto_build_proto_rawDescOnce sync.Once
	file_pb_build_proto_build_proto_rawDescData []byte
)

func file_pb_build_proto_build_proto_rawDescGZIP() []byte {
	file_pb_build_proto_build_proto_rawDescOnce.Do(func() {
		file_pb_build_proto_build_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_build_proto_build_proto_rawDesc), len(file_pb_build_proto_build_proto_rawDesc)))
	})
	return file_pb_build_proto_build_proto_rawDescData
}

var file_pb_build_proto_build_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pb_build_proto_build_proto_goTypes = []any{
	(*Build)(nil), // 0: build_proto.Build
}
var file_pb_build_proto_build_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pb_build_proto_build_proto_init() }
func file_pb_build_proto_build_proto_init() {
	if File_pb_build_proto_build_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_build_proto_build_proto_rawDesc), len(file_pb_build_proto_build_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_build_proto_build_proto_goTypes,
		DependencyIndexes: file_pb_build_proto_build_proto_depIdxs,
		MessageInfos:      file_pb_build_proto_build_proto_msgTypes,
	}.Build()
	File_pb_build_proto_build_proto = out.File
	file_pb_build_proto_build_proto_goTypes = nil
	file_pb_build_proto_build_proto_depIdxs = nil
}
