// Copyright 2015 Google Inc. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//
// Protocol buffer containing information about installed packages.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: pb/usagestats_proto/android_battery_usage.proto

package usagestats_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SystemInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Installed Package List
	InstalledPackages []*PackageInfo `protobuf:"bytes,1,rep,name=installed_packages,json=installedPackages" json:"installed_packages,omitempty"`
	// e.g. hammerhead-userdebug L MASTER eng.xx... dev-keys Build
	BuildDisplay *string `protobuf:"bytes,2,opt,name=build_display,json=buildDisplay" json:"build_display,omitempty"`
	// e.g. google/hammerhead/hammerhead:L/MASTER/
	//
	//	eng.abcd.20140304.184123:userdebug/dev-keys
	BuildFingerprint *string `protobuf:"bytes,3,opt,name=build_fingerprint,json=buildFingerprint" json:"build_fingerprint,omitempty"`
	// Bootloader version e.g. HHZ11k
	Bootloader *string `protobuf:"bytes,4,opt,name=bootloader" json:"bootloader,omitempty"`
	// e.g. T-Mobile
	NetworkOperator *string `protobuf:"bytes,5,opt,name=network_operator,json=networkOperator" json:"network_operator,omitempty"`
	// e.g. userdebug
	BuildType *string `protobuf:"bytes,6,opt,name=build_type,json=buildType" json:"build_type,omitempty"`
	// e.g. hammerhead
	Device *string `protobuf:"bytes,7,opt,name=device" json:"device,omitempty"`
	// e.g. M8974A-2.0.50.1.02
	BasebandRadio *string `protobuf:"bytes,8,opt,name=baseband_radio,json=basebandRadio" json:"baseband_radio,omitempty"`
	// e.g. hammerhead
	Hardware *string `protobuf:"bytes,9,opt,name=hardware" json:"hardware,omitempty"`
	// Checkin/OTA groups for the device
	//
	//	e.g. auto.droidfood, auto.googlefood.lmp
	Groups []string `protobuf:"bytes,10,rep,name=groups" json:"groups,omitempty"`
	// e.g. 22
	SdkVersion *int32 `protobuf:"varint,11,opt,name=sdk_version,json=sdkVersion" json:"sdk_version,omitempty"`
	// e.g. ES
	CountryCode *string `protobuf:"bytes,12,opt,name=country_code,json=countryCode" json:"country_code,omitempty"`
	// e.g. Europe/London
	TimeZone      *string `protobuf:"bytes,13,opt,name=time_zone,json=timeZone" json:"time_zone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemInfo) Reset() {
	*x = SystemInfo{}
	mi := &file_pb_usagestats_proto_android_battery_usage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemInfo) ProtoMessage() {}

func (x *SystemInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pb_usagestats_proto_android_battery_usage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemInfo.ProtoReflect.Descriptor instead.
func (*SystemInfo) Descriptor() ([]byte, []int) {
	return file_pb_usagestats_proto_android_battery_usage_proto_rawDescGZIP(), []int{0}
}

func (x *SystemInfo) GetInstalledPackages() []*PackageInfo {
	if x != nil {
		return x.InstalledPackages
	}
	return nil
}

func (x *SystemInfo) GetBuildDisplay() string {
	if x != nil && x.BuildDisplay != nil {
		return *x.BuildDisplay
	}
	return ""
}

func (x *SystemInfo) GetBuildFingerprint() string {
	if x != nil && x.BuildFingerprint != nil {
		return *x.BuildFingerprint
	}
	return ""
}

func (x *SystemInfo) GetBootloader() string {
	if x != nil && x.Bootloader != nil {
		return *x.Bootloader
	}
	return ""
}

func (x *SystemInfo) GetNetworkOperator() string {
	if x != nil && x.NetworkOperator != nil {
		return *x.NetworkOperator
	}
	return ""
}

func (x *SystemInfo) GetBuildType() string {
	if x != nil && x.BuildType != nil {
		return *x.BuildType
	}
	return ""
}

func (x *SystemInfo) GetDevice() string {
	if x != nil && x.Device != nil {
		return *x.Device
	}
	return ""
}

func (x *SystemInfo) GetBasebandRadio() string {
	if x != nil && x.BasebandRadio != nil {
		return *x.BasebandRadio
	}
	return ""
}

func (x *SystemInfo) GetHardware() string {
	if x != nil && x.Hardware != nil {
		return *x.Hardware
	}
	return ""
}

func (x *SystemInfo) GetGroups() []string {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *SystemInfo) GetSdkVersion() int32 {
	if x != nil && x.SdkVersion != nil {
		return *x.SdkVersion
	}
	return 0
}

func (x *SystemInfo) GetCountryCode() string {
	if x != nil && x.CountryCode != nil {
		return *x.CountryCode
	}
	return ""
}

func (x *SystemInfo) GetTimeZone() string {
	if x != nil && x.TimeZone != nil {
		return *x.TimeZone
	}
	return ""
}

var File_pb_usagestats_proto_android_battery_usage_proto protoreflect.FileDescriptor

const file_pb_usagestats_proto_android_battery_usage_proto_rawDesc = "" +
	"\n" +
	"/pb/usagestats_proto/android_battery_usage.proto\x12\x10usagestats_proto\x1a.pb/usagestats_proto/android_package_info.proto\"\xea\x03\n" +
	"\n" +
	"SystemInfo\x12L\n" +
	"\x12installed_packages\x18\x01 \x03(\v2\x1d.usagestats_proto.PackageInfoR\x11installedPackages\x12#\n" +
	"\rbuild_display\x18\x02 \x01(\tR\fbuildDisplay\x12+\n" +
	"\x11build_fingerprint\x18\x03 \x01(\tR\x10buildFingerprint\x12\x1e\n" +
	"\n" +
	"bootloader\x18\x04 \x01(\tR\n" +
	"bootloader\x12)\n" +
	"\x10network_operator\x18\x05 \x01(\tR\x0fnetworkOperator\x12\x1d\n" +
	"\n" +
	"build_type\x18\x06 \x01(\tR\tbuildType\x12\x16\n" +
	"\x06device\x18\a \x01(\tR\x06device\x12%\n" +
	"\x0ebaseband_radio\x18\b \x01(\tR\rbasebandRadio\x12\x1a\n" +
	"\bhardware\x18\t \x01(\tR\bhardware\x12\x16\n" +
	"\x06groups\x18\n" +
	" \x03(\tR\x06groups\x12\x1f\n" +
	"\vsdk_version\x18\v \x01(\x05R\n" +
	"sdkVersion\x12!\n" +
	"\fcountry_code\x18\f \x01(\tR\vcountryCode\x12\x1b\n" +
	"\ttime_zone\x18\r \x01(\tR\btimeZoneB9Z7github.com/google/battery-historian/pb/usagestats_proto"

var (
	file_pb_usagestats_proto_android_battery_usage_proto_rawDescOnce sync.Once
	file_pb_usagestats_proto_android_battery_usage_proto_rawDescData []byte
)

func file_pb_usagestats_proto_android_battery_usage_proto_rawDescGZIP() []byte {
	file_pb_usagestats_proto_android_battery_usage_proto_rawDescOnce.Do(func() {
		file_pb_usagestats_proto_android_battery_usage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_usagestats_proto_android_battery_usage_proto_rawDesc), len(file_pb_usagestats_proto_android_battery_usage_proto_rawDesc)))
	})
	return file_pb_usagestats_proto_android_battery_usage_proto_rawDescData
}

var file_pb_usagestats_proto_android_battery_usage_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pb_usagestats_proto_android_battery_usage_proto_goTypes = []any{
	(*SystemInfo)(nil),  // 0: usagestats_proto.SystemInfo
	(*PackageInfo)(nil), // 1: usagestats_proto.PackageInfo
}
var file_pb_usagestats_proto_android_battery_usage_proto_depIdxs = []int32{
	1, // 0: usagestats_proto.SystemInfo.installed_packages:type_name -> usagestats_proto.PackageInfo
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pb_usagestats_proto_android_battery_usage_proto_init() }
func file_pb_usagestats_proto_android_battery_usage_proto_init() {
	if File_pb_usagestats_proto_android_battery_usage_proto != nil {
		return
	}
	file_pb_usagestats_proto_android_package_info_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_usagestats_proto_android_battery_usage_proto_rawDesc), len(file_pb_usagestats_proto_android_battery_usage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_usagestats_proto_android_battery_usage_proto_goTypes,
		DependencyIndexes: file_pb_usagestats_proto_android_battery_usage_proto_depIdxs,
		MessageInfos:      file_pb_usagestats_proto_android_battery_usage_proto_msgTypes,
	}.Build()
	File_pb_usagestats_proto_android_battery_usage_proto = out.File
	file_pb_usagestats_proto_android_battery_usage_proto_goTypes = nil
	file_pb_usagestats_proto_android_battery_usage_proto_depIdxs = nil
}
