// Copyright 2016 Google Inc. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//
// Protocol buffer containing information about installed packages.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: pb/usagestats_proto/android_package_info.proto

package usagestats_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PackageInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Apps / service name. (e.g. com.google.android.apps.books)
	PkgName *string `protobuf:"bytes,1,req,name=pkg_name,json=pkgName" json:"pkg_name,omitempty"`
	// App version number
	VersionCode *int32 `protobuf:"varint,2,opt,name=version_code,json=versionCode" json:"version_code,omitempty"`
	// Version name
	VersionName *string `protobuf:"bytes,3,opt,name=version_name,json=versionName" json:"version_name,omitempty"`
	// First install time
	FirstInstallTime *int64 `protobuf:"varint,4,opt,name=first_install_time,json=firstInstallTime" json:"first_install_time,omitempty"`
	// Last update time
	LastUpdateTime *int64 `protobuf:"varint,5,opt,name=last_update_time,json=lastUpdateTime" json:"last_update_time,omitempty"`
	// The sharedUserId assigned to this package by the device.
	Uid *int32 `protobuf:"varint,6,opt,name=uid" json:"uid,omitempty"`
	// The string label of the sharedUserId this package claims, if any.
	SharedUserId *string `protobuf:"bytes,7,opt,name=shared_user_id,json=sharedUserId" json:"shared_user_id,omitempty"`
	// Whether or not the package is a system app (was installed in the device's
	// system image).
	// http://developer.android.com/reference/android/content/pm/ApplicationInfo.html#FLAG_SYSTEM
	IsSystemApp *bool `protobuf:"varint,8,opt,name=is_system_app,json=isSystemApp" json:"is_system_app,omitempty"`
	// Whether or not the package has been installed as an update to a built-in
	// system app. This boolean is meaningless if is_system_app is false.
	// http://developer.android.com/reference/android/content/pm/ApplicationInfo.html#FLAG_UPDATED_SYSTEM_APP
	IsUpdatedSystemApp *bool `protobuf:"varint,9,opt,name=is_updated_system_app,json=isUpdatedSystemApp" json:"is_updated_system_app,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PackageInfo) Reset() {
	*x = PackageInfo{}
	mi := &file_pb_usagestats_proto_android_package_info_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PackageInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackageInfo) ProtoMessage() {}

func (x *PackageInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pb_usagestats_proto_android_package_info_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackageInfo.ProtoReflect.Descriptor instead.
func (*PackageInfo) Descriptor() ([]byte, []int) {
	return file_pb_usagestats_proto_android_package_info_proto_rawDescGZIP(), []int{0}
}

func (x *PackageInfo) GetPkgName() string {
	if x != nil && x.PkgName != nil {
		return *x.PkgName
	}
	return ""
}

func (x *PackageInfo) GetVersionCode() int32 {
	if x != nil && x.VersionCode != nil {
		return *x.VersionCode
	}
	return 0
}

func (x *PackageInfo) GetVersionName() string {
	if x != nil && x.VersionName != nil {
		return *x.VersionName
	}
	return ""
}

func (x *PackageInfo) GetFirstInstallTime() int64 {
	if x != nil && x.FirstInstallTime != nil {
		return *x.FirstInstallTime
	}
	return 0
}

func (x *PackageInfo) GetLastUpdateTime() int64 {
	if x != nil && x.LastUpdateTime != nil {
		return *x.LastUpdateTime
	}
	return 0
}

func (x *PackageInfo) GetUid() int32 {
	if x != nil && x.Uid != nil {
		return *x.Uid
	}
	return 0
}

func (x *PackageInfo) GetSharedUserId() string {
	if x != nil && x.SharedUserId != nil {
		return *x.SharedUserId
	}
	return ""
}

func (x *PackageInfo) GetIsSystemApp() bool {
	if x != nil && x.IsSystemApp != nil {
		return *x.IsSystemApp
	}
	return false
}

func (x *PackageInfo) GetIsUpdatedSystemApp() bool {
	if x != nil && x.IsUpdatedSystemApp != nil {
		return *x.IsUpdatedSystemApp
	}
	return false
}

var File_pb_usagestats_proto_android_package_info_proto protoreflect.FileDescriptor

const file_pb_usagestats_proto_android_package_info_proto_rawDesc = "" +
	"\n" +
	".pb/usagestats_proto/android_package_info.proto\x12\x10usagestats_proto\"\xd5\x02\n" +
	"\vPackageInfo\x12\x19\n" +
	"\bpkg_name\x18\x01 \x02(\tR\apkgName\x12!\n" +
	"\fversion_code\x18\x02 \x01(\x05R\vversionCode\x12!\n" +
	"\fversion_name\x18\x03 \x01(\tR\vversionName\x12,\n" +
	"\x12first_install_time\x18\x04 \x01(\x03R\x10firstInstallTime\x12(\n" +
	"\x10last_update_time\x18\x05 \x01(\x03R\x0elastUpdateTime\x12\x10\n" +
	"\x03uid\x18\x06 \x01(\x05R\x03uid\x12$\n" +
	"\x0eshared_user_id\x18\a \x01(\tR\fsharedUserId\x12\"\n" +
	"\ris_system_app\x18\b \x01(\bR\visSystemApp\x121\n" +
	"\x15is_updated_system_app\x18\t \x01(\bR\x12isUpdatedSystemAppB9Z7github.com/google/battery-historian/pb/usagestats_proto"

var (
	file_pb_usagestats_proto_android_package_info_proto_rawDescOnce sync.Once
	file_pb_usagestats_proto_android_package_info_proto_rawDescData []byte
)

func file_pb_usagestats_proto_android_package_info_proto_rawDescGZIP() []byte {
	file_pb_usagestats_proto_android_package_info_proto_rawDescOnce.Do(func() {
		file_pb_usagestats_proto_android_package_info_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_usagestats_proto_android_package_info_proto_rawDesc), len(file_pb_usagestats_proto_android_package_info_proto_rawDesc)))
	})
	return file_pb_usagestats_proto_android_package_info_proto_rawDescData
}

var file_pb_usagestats_proto_android_package_info_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pb_usagestats_proto_android_package_info_proto_goTypes = []any{
	(*PackageInfo)(nil), // 0: usagestats_proto.PackageInfo
}
var file_pb_usagestats_proto_android_package_info_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pb_usagestats_proto_android_package_info_proto_init() }
func file_pb_usagestats_proto_android_package_info_proto_init() {
	if File_pb_usagestats_proto_android_package_info_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_usagestats_proto_android_package_info_proto_rawDesc), len(file_pb_usagestats_proto_android_package_info_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_usagestats_proto_android_package_info_proto_goTypes,
		DependencyIndexes: file_pb_usagestats_proto_android_package_info_proto_depIdxs,
		MessageInfos:      file_pb_usagestats_proto_android_package_info_proto_msgTypes,
	}.Build()
	File_pb_usagestats_proto_android_package_info_proto = out.File
	file_pb_usagestats_proto_android_package_info_proto_goTypes = nil
	file_pb_usagestats_proto_android_package_info_proto_depIdxs = nil
}
