// Copyright 2015 Google Inc. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//
// Protocol buffer containing information about installed packages.
// A Session consists of the battery summary of a day for a device.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: pb/session_proto/session.proto

package session_proto

import (
	usagestats_proto "github.com/google/battery-historian/pb/usagestats_proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Aggregated checkin stats that we will use to compute deltas.
type Checkin struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	AndroidId *int64                 `protobuf:"varint,1,opt,name=android_id,json=androidId" json:"android_id,omitempty"`
	// Build fingerprint
	BuildFingerprint *string `protobuf:"bytes,2,opt,name=build_fingerprint,json=buildFingerprint" json:"build_fingerprint,omitempty"`
	// Device
	Device *string `protobuf:"bytes,3,opt,name=device" json:"device,omitempty"`
	// Timestamp of measurement
	BucketSnapshotMsec *int64 `protobuf:"varint,4,opt,name=bucket_snapshot_msec,json=bucketSnapshotMsec" json:"bucket_snapshot_msec,omitempty"`
	// Duration of the collection
	BucketDurationMsec *int64 `protobuf:"varint,5,opt,name=bucket_duration_msec,json=bucketDurationMsec" json:"bucket_duration_msec,omitempty"`
	// Checkin
	Checkin *string `protobuf:"bytes,6,opt,name=checkin" json:"checkin,omitempty"`
	// Installed packages
	Packages []*usagestats_proto.PackageInfo `protobuf:"bytes,7,rep,name=packages" json:"packages,omitempty"`
	// Checkin/OTA groups for the device
	//
	//	e.g. auto.droidfood, auto.googlefood.lmp
	Groups []string `protobuf:"bytes,10,rep,name=groups" json:"groups,omitempty"`
	// System info uploaded directly from the device.
	SystemInfo    *usagestats_proto.SystemInfo `protobuf:"bytes,8,opt,name=system_info,json=systemInfo" json:"system_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Checkin) Reset() {
	*x = Checkin{}
	mi := &file_pb_session_proto_session_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Checkin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Checkin) ProtoMessage() {}

func (x *Checkin) ProtoReflect() protoreflect.Message {
	mi := &file_pb_session_proto_session_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Checkin.ProtoReflect.Descriptor instead.
func (*Checkin) Descriptor() ([]byte, []int) {
	return file_pb_session_proto_session_proto_rawDescGZIP(), []int{0}
}

func (x *Checkin) GetAndroidId() int64 {
	if x != nil && x.AndroidId != nil {
		return *x.AndroidId
	}
	return 0
}

func (x *Checkin) GetBuildFingerprint() string {
	if x != nil && x.BuildFingerprint != nil {
		return *x.BuildFingerprint
	}
	return ""
}

func (x *Checkin) GetDevice() string {
	if x != nil && x.Device != nil {
		return *x.Device
	}
	return ""
}

func (x *Checkin) GetBucketSnapshotMsec() int64 {
	if x != nil && x.BucketSnapshotMsec != nil {
		return *x.BucketSnapshotMsec
	}
	return 0
}

func (x *Checkin) GetBucketDurationMsec() int64 {
	if x != nil && x.BucketDurationMsec != nil {
		return *x.BucketDurationMsec
	}
	return 0
}

func (x *Checkin) GetCheckin() string {
	if x != nil && x.Checkin != nil {
		return *x.Checkin
	}
	return ""
}

func (x *Checkin) GetPackages() []*usagestats_proto.PackageInfo {
	if x != nil {
		return x.Packages
	}
	return nil
}

func (x *Checkin) GetGroups() []string {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *Checkin) GetSystemInfo() *usagestats_proto.SystemInfo {
	if x != nil {
		return x.SystemInfo
	}
	return nil
}

var File_pb_session_proto_session_proto protoreflect.FileDescriptor

const file_pb_session_proto_session_proto_rawDesc = "" +
	"\n" +
	"\x1epb/session_proto/session.proto\x12\rsession_proto\x1a/pb/usagestats_proto/android_battery_usage.proto\x1a.pb/usagestats_proto/android_package_info.proto\"\xfd\x02\n" +
	"\aCheckin\x12\x1d\n" +
	"\n" +
	"android_id\x18\x01 \x01(\x03R\tandroidId\x12+\n" +
	"\x11build_fingerprint\x18\x02 \x01(\tR\x10buildFingerprint\x12\x16\n" +
	"\x06device\x18\x03 \x01(\tR\x06device\x120\n" +
	"\x14bucket_snapshot_msec\x18\x04 \x01(\x03R\x12bucketSnapshotMsec\x120\n" +
	"\x14bucket_duration_msec\x18\x05 \x01(\x03R\x12bucketDurationMsec\x12\x18\n" +
	"\acheckin\x18\x06 \x01(\tR\acheckin\x129\n" +
	"\bpackages\x18\a \x03(\v2\x1d.usagestats_proto.PackageInfoR\bpackages\x12\x16\n" +
	"\x06groups\x18\n" +
	" \x03(\tR\x06groups\x12=\n" +
	"\vsystem_info\x18\b \x01(\v2\x1c.usagestats_proto.SystemInfoR\n" +
	"systemInfoB6Z4github.com/google/battery-historian/pb/session_proto"

var (
	file_pb_session_proto_session_proto_rawDescOnce sync.Once
	file_pb_session_proto_session_proto_rawDescData []byte
)

func file_pb_session_proto_session_proto_rawDescGZIP() []byte {
	file_pb_session_proto_session_proto_rawDescOnce.Do(func() {
		file_pb_session_proto_session_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_session_proto_session_proto_rawDesc), len(file_pb_session_proto_session_proto_rawDesc)))
	})
	return file_pb_session_proto_session_proto_rawDescData
}

var file_pb_session_proto_session_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pb_session_proto_session_proto_goTypes = []any{
	(*Checkin)(nil),                      // 0: session_proto.Checkin
	(*usagestats_proto.PackageInfo)(nil), // 1: usagestats_proto.PackageInfo
	(*usagestats_proto.SystemInfo)(nil),  // 2: usagestats_proto.SystemInfo
}
var file_pb_session_proto_session_proto_depIdxs = []int32{
	1, // 0: session_proto.Checkin.packages:type_name -> usagestats_proto.PackageInfo
	2, // 1: session_proto.Checkin.system_info:type_name -> usagestats_proto.SystemInfo
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pb_session_proto_session_proto_init() }
func file_pb_session_proto_session_proto_init() {
	if File_pb_session_proto_session_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_session_proto_session_proto_rawDesc), len(file_pb_session_proto_session_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_session_proto_session_proto_goTypes,
		DependencyIndexes: file_pb_session_proto_session_proto_depIdxs,
		MessageInfos:      file_pb_session_proto_session_proto_msgTypes,
	}.Build()
	File_pb_session_proto_session_proto = out.File
	file_pb_session_proto_session_proto_goTypes = nil
	file_pb_session_proto_session_proto_depIdxs = nil
}
